name: skype
version: 8.63.76.77
summary: Skype
description: Skype keeps the world talking, for free.
    Skype keeps you together. Call, message and share with others.
    * It's free to download and join.
    * Call, instant message and send photos and documents to anyone else on Skype.
    * Easily text message anywhere in the world.
    * Get your friends together on a group call.
    And that's just the start...
grade: stable
confinement: strict
base: core18

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

parts:
    skype:
        plugin: dump
        source: https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.63.76.77_amd64.deb
        stage-packages:
            - libasound2
            - libgconf-2-4
            - libnspr4
            - libnss3
            - libstdc++6
            - libv4l-0
            - libxss1
            - libappindicator3-1
            - libsecret-1-0
        prime:
            - -usr/share/lintian
            - -usr/share/man
            - -opt

    skype-wrapper:
        plugin: dump
        source: files
        organize:
            'skype-wrapper': bin/

    preloads:
      source: https://github.com/snapcore/snapcraft-preloads.git
      source-branch: fixes
      plugin: make

apps:
    skype:
        autostart: skypeforlinux.desktop
        command-chain: [bin/skype-wrapper]
        command: usr/share/skypeforlinux/skypeforlinux
        environment:
            # Correct the TMPDIR path for Chromium Framework/Electron to
            # ensure libappindicator has readable resources
            TMPDIR: $XDG_RUNTIME_DIR
            # Coerce XDG_CURRENT_DESKTOP to Unity so that App Indicators
            # are used and do not fall back to Notification Area applets
            # or disappear completely.
            XDG_CURRENT_DESKTOP: Unity
            # Fallback to XWayland if running in a Wayland session.
            DISABLE_WAYLAND: 1
            LD_PRELOAD: $SNAP/libpreload-bindtextdomain.so:$SNAP/libpreload-chromium-content-api.so:$SNAP/libpreload-semaphores.so
            SHM_CHROMIUM_DEBUG: 1
        extensions: [gnome-3-28]
        plugs:
            - bluez
            - browser-support
            - camera
            - desktop
            - desktop-legacy
            - gsettings
            - home
            - mount-observe
            - network
            - network-observe
            - opengl
            - password-manager-service
            - pulseaudio
            - screen-inhibit-control
            - unity7
            - wayland
            - x11
