name: skype
version: 64-preview
summary: Skype
description: Skype keeps the world talking, for free.
    Skype keeps you together. Call, message and share with others.
    * It's free to download and join.
    * Call, instant message and send photos and documents to anyone else on Skype.
    * Easily text message anywhere in the world.
    * Get your friends together on a group call.
    And that's just the start...
grade: stable
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

parts:
    snapcraft-desktop-helpers:
        source: git://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: gtk
        plugin: make
        make-parameters: ["FLAVOR=gtk3"]
        build-packages:
        - build-essential
        - libgtk-3-dev
        override-build: |
          snapcraftctl build
          mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

    skype:
        plugin: dump
        source: https://go.skype.com/skypeforlinux-64-preview.deb
        after:
            - snapcraft-desktop-helpers
        stage-packages:
            - libasound2
            - libgconf-2-4
            - libnspr4
            - libnss3
            - libstdc++6
            - libv4l-0
            - libxss1
            - libappindicator3-1
        override-build: |
            snapcraftctl build
            #sed -i 's|.org.chromium.Chromium.XXXXXX|snap.skype.xx.Chromium.XXXXXX|g' $SNAPCRAFT_PART_INSTALL/usr/share/skypeforlinux/skypeforlinux
        prime:
            - -usr/share/lintian
            - -usr/share/man
            - -opt

    skype-wrapper:
        plugin: dump
        source: files
        organize:
            'skype-wrapper': bin/

    skype-shm-preloader:
        plugin: cmake
        source: shm-preloader
        build-packages:
            - on amd64:
                - gcc-multilib
                - g++-multilib

apps:
    skype:
        autostart: skypeforlinux.desktop
        command: bin/desktop-launch ${SNAP}/bin/skype-wrapper
        environment:
            # Correct the TMPDIR path for Chromium Framework/Electron to
            # ensure libappindicator has readable resources
            TMPDIR: $XDG_RUNTIME_DIR
            # Coerce XDG_CURRENT_DESKTOP to Unity so that App Indicators
            # are used and do not fall back to Notification Area applets
            # or disappear completely.
            XDG_CURRENT_DESKTOP: Unity
            # Fallback to XWayland if running in a Wayland session.
            DISABLE_WAYLAND: 1
        plugs:
            - bluez
            - browser-support
            - camera
            - desktop
            - desktop-legacy
            - gsettings
            - home
            - mount-observe
            - network
            - network-observe
            - opengl
            - password-manager-service
            - pulseaudio
            - screen-inhibit-control
            - unity7
            - wayland
            - x11
